services:
  server:
    build: ./server
    env_file:
      - .env
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped

  client:
    build: ./client
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - services

networks:
  services:
    external: true
